# Generated by Django 5.2.6 on 2026-04-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_userprofile_websitevisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The regular, everyday price.', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Enter a number from 0 to 100.'),
        ),
    ]
