# Generated by Django 6.0.4 on 2026-05-06 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008 livestreambroadcast livestreamcomment '),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestreambroadcast',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional: link to a Flash Sale Event. When this stream goes live, that event activates automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livestreams', to='api.event'),
        ),
        migrations.AlterField(
            model_name='livestreambroadcast',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Toggle ON to make this the active broadcast. Only one stream can be live at a time.'),
        ),
        migrations.AlterField(
            model_name='livestreambroadcast',
            name='video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID (e.g. dQw4w9WgXcQ). Find it in the YouTube Studio stream URL.', max_length=50),
        ),
        migrations.AlterField(
            model_name='livestreamcomment',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hidden comments are not shown to viewers'),
        ),
    ]
